// fs/fs_react_udemy/code/react/src/app/Footer.js
export default function Footer()
{
    return(
        <div className="container-fluid py-3">
            <div className="row">
                <div className="col-md-6">
                    CAP_REACT.
                </div>
                <div className="col-md-6 text-right">
                    made by <a href="http://localhost:3000/">Luis</a>
                </div>
            </div>
        </div>
    )

}

// fs_angular_udemy/angular/src/app/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'footer-component',
  template:`
    <footer class="container-fluid">
      <div class="row">
        <div class="col-12">
          <hr/>
          this is the footer!
        </div>
      </div>
    </footer>
  `
})
export class FooterComponent implements OnInit 
{
 
  ngOnInit()
  {

  }
}
